version: '3.7'

services:
  my-app:
    build: .
    ports:
      - 8080:8080
    networks:
      - s-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: collegeproject
    networks:
      - s-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - mysql-volu:/var/lib/mysql

networks:
  s-network:
    driver: bridge

volumes:
  mysql-volu: